In [8]:
!pip install hummingbird-ml # It helps to convert ml models into pytorch.

In [9]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from hummingbird.ml import convert

In [10]:
# Create some random data for binary classification

num_classes=2
X=np.array(np.random.rand(100000,28),dtype=np.float32)
y=np.random.randint(num_classes,size=100000)

In [11]:
# Create and train model

sk_model=RandomForestClassifier(n_estimators=10,max_depth=10)
sk_model.fit(X,y)

RandomForestClassifier(max_depth=10, n_estimators=10)

In [12]:
X

array([[0.05467549, 0.1526581 , 0.7009528 , ..., 0.9777392 , 0.9864897 ,
        0.7122489 ],
       [0.43344277, 0.7559071 , 0.6529962 , ..., 0.4012803 , 0.92499775,
        0.8456036 ],
       [0.05551035, 0.16489194, 0.34620148, ..., 0.47421494, 0.11528774,
        0.8257275 ],
       ...,
       [0.15317729, 0.8838371 , 0.7382156 , ..., 0.28810224, 0.0788473 ,
        0.57155865],
       [0.722401  , 0.22472611, 0.6428455 , ..., 0.49046245, 0.38483328,
        0.72573674],
       [0.48421052, 0.24482249, 0.8204175 , ..., 0.4410312 , 0.12954882,
        0.5696577 ]], dtype=float32)

In [13]:
y

array([0, 1, 0, ..., 1, 1, 0])

In [14]:
# Use hummingbird to convert the traditional ml model into pytorch.

model=convert(sk_model,'pytorch')

In [18]:
# Run hummingbird on CPU
%%timeit -r 3
model.predict(X)

8.34 ms ± 33.2 µs per loop (mean ± std. dev. of 3 runs, 100 loops each)


In [19]:
# Run predictions on GPU
%%time
model.to('cuda') # cuda is the library to predict by GPU
model.predict(X)

CPU times: user 9.84 ms, sys: 989 µs, total: 10.8 ms
Wall time: 11.1 ms


array([0, 1, 1, ..., 1, 1, 0])